---
- hosts: all
  tasks:
    - name: add gnome3 ppa repository
      apt_repository: repo='ppa:gnome3-team/gnome3' state=present filename='gnome3-team'

    - name: add libreoffice ppa repository
      apt_repository: repo='ppa:libreoffice/ppa' state=present filename='gnome3-team'

    - name: add google-chrome repository key
      apt_key: url='https://dl-ssl.google.com/linux/linux_signing_key.pub' state=present

    - name: add google-chrome repository
      apt_repository: repo='deb http://dl.google.com/linux/chrome/deb/ stable main' state=present filename='google-chrome'

    - name: add virtualbox repository key
      apt_key: url='http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc' state=present

    - name: add virtualbox repository
      apt_repository: repo='deb http://download.virtualbox.org/virtualbox/debian xenial non-free contrib' state=present filename='virtualbox'    

    # - name: add mozilla ppa repository
    #   apt_repository: repo='ppa:ubuntu-mozilla-daily/ppa ' state=present filename='mozilla'

    # - name: add ubuntu-wine ppa repository
    #   apt_repository: repo='ppa:ubuntu-wine/ppa ' state=present filename='ubuntu-wine'

    - name: add numix-theme ppa repository
      apt_repository: repo='ppa:numix/ppa' state=present filename='numix'

    - name: add atom repository
      apt_repository: repo='ppa:webupd8team/atom' state=present

    - name: add vlc repository
      apt_repository: repo='ppa:videolan/stable-daily' state=present

    - name: add sublime-text ppa repository
      apt_repository: repo='ppa:webupd8team/sublime-text-3' state=present

    - name: add java ppa repository
      apt_repository: repo='ppa:webupd8team/java' state=present

    - name: add ubuntu-wine ppa repository
      apt_repository: repo='ppa:ubuntu-wine/ppa' state=present

    - name: add pipelight ppa repository
      apt_repository: repo='ppa:pipelight/stable' state=present

    - name: add y-ppa-manager ppa repository
      apt_repository: repo='ppa:webupd8team/y-ppa-manager' state=present

    # disable for now
    # - name: add mc3man repository key
    #   apt_key: keyserver='keyserver.ubuntu.com' id='8E51A6D660CD88D67D65221D90BD7EACED8E640A' state=present

    # - name: add mc3man repository
    #   apt_repository: repo='deb http://ppa.launchpad.net/mc3man/trusty-media/ubuntu trusty main' state=present filename='mc3man-trusty'

    # waiting for xenial
    # - name: add themes ppa repository
    #   apt_repository: repo='ppa:webupd8team/themes' state=present

    # - name: add pidgin ppa repository
    #   apt_repository: repo='ppa:pidgin-developers/ppa' state=present

    - name: add anoise ppa repository
      apt_repository: repo='ppa:costales/anoise' state=present filename='anoise'

    - name: add docker repository key
      apt_key: keyserver='p80.pool.sks-keyservers.net' id='58118E89F3A912897C070ADBF76221572C52609D' state=present

    - name: add docker repository
      apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present filename='docker'

    - name: add dropbox repository key
      apt_key: keyserver='pgp.mit.edu' id='5044912E' state=present

    - name: add dropbox repository
      apt_repository: repo='deb [arch=i386,amd64] http://linux.dropbox.com/ubuntu xenial main' state=present filename='dropbox'

    - name: add fish-shell ppa repository
      apt_repository: repo='ppa:fish-shell/release-2' state=present filename='fish-shell'

    - name: add erlang-solutions repository key
      apt_key: url='https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc' state=present

    - name: add erlang-solutions repository
      apt_repository: repo='deb https://packages.erlang-solutions.com/ubuntu xenial contrib' state=present filename='erlang-solutions'